# Generated by Django 5.0.6 on 2024-05-28 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterOrderWithRespectTo(
            name='producto',
            order_with_respect_to='descripcion',
        ),
    ]
